### ISSUE TITLE
make "meta included false" on relationships optional?

### ISSUE THREAD

**Issue by nruth** [jsonapi-rb/jsonapi-serializable#109]
like in #90 

This causes issues with some client libraries (throwing away previously loaded relationship data), and generally seems unnecessary. Is there a compelling reason for this being on by default and having no way to turn it off?

**Comment by beauby** [comment]
The reason is that [the spec](https://jsonapi.org/format/#document-resource-object-relationships) states:
> A “relationship object” MUST contain at least one of the following:
>
> + links: a links object containing at least one of the following:
>   [...]
> + data: resource linkage
> + meta: a meta object that contains non-standard meta-information about the relationship.

If you do provide a `link` definition for your relationship, the `meta: { included: false}` will disappear. However, if there is neither a `data` member, nor a `links` member, the spec forces us to have a `meta` member.

**Comment by nruth** [comment]
I see something different in the spec. If you scroll up to https://jsonapi.org/format/#document-resource-objects (screenshot attached) it says saying you must include `id` and `type` but everything else is optional. So the relationships key can be omitted entirely, meaning you can skip this bit about links/data/meta.

![Screenshot 2019-04-05 at 17 33 13](https://user-images.githubusercontent.com/26158/55642856-961c7080-57c9-11e9-925e-e0086489fc0c.png)

From looking at "MAY" in https://tools.ietf.org/html/rfc2119 what you're doing is perhaps fine, but it still seems unnecessary and is breaking ember-data and I think led me to post-process the json to delete those keys.

**Comment by beauby** [comment]
> it says saying you must include id and type but everything else is optional. So the relationships key can be omitted entirely, meaning you can skip this bit about links/data/meta.

That would make for a valid payload in general, but not for a valid response unless the relationship in question was explicitly discarded via sparse fieldsets.

**Comment by nruth** [comment]
Valid according to what? Could you point that out in the spec?

**Comment by Diasporism** [comment]
Yeah I have to side with @nruth on this one. The `relationships` node is optional and JSON API spec never requires it _unless_ a client asks for an associated record via the `include` param.

I'm not against it always existing, but the way it's implemented in this library is actually broken and causing bugs. I've opened a related issue [here](https://github.com/jsonapi-rb/jsonapi-serializable/issues/124) and a PR to fix it by just removing it altogether. My reasonings are explained in the other issue and I'm open for debate over there.
