### ISSUE TITLE
0.3.1 Breaks consumers

### ISSUE THREAD

**Issue by wadetandy** [jsonapi-rb/jsonapi-serializable#111]
The graphiti project does not work with yesterday's release of 0.3.1.  As you can see from [this PR](https://github.com/graphiti-api/graphiti/pull/104), upgrading from 0.3.0 to 0.3.1 is now breaking our specs.  While we had previously been correctly inferring serializers during render, this new version changes some internal APIs such that that doesn't work anymore.

**Comment by dawidof** [comment]
@wadetandy **jsonapi-serializable** by default requires to have a serializer.

As I've understood, in **graphiti**  it's overridden here
https://github.com/graphiti-api/graphiti/blob/d737072540372680178b2bfef05f037e00880638/lib/graphiti/jsonapi_serializable_ext.rb#L9
https://github.com/graphiti-api/graphiti/blob/d737072540372680178b2bfef05f037e00880638/lib/graphiti/jsonapi_serializable_ext.rb#L41

What changed in **json-serializable**
https://github.com/jsonapi-rb/jsonapi-serializable/commit/914ccdecef9ec8b6f7ebca96bada5825fe99408f#diff-7ab185235df66320d19f12a08187bd07L87
to
https://github.com/jsonapi-rb/jsonapi-serializable/commit/914ccdecef9ec8b6f7ebca96bada5825fe99408f#diff-48af34220c771a8bce480a68067946e5R24


If you need help, please let me know.

**Comment by wadetandy** [comment]
Thanks for the quick help!  Fixed in graphiti-api/graphiti#106.
