### ISSUE TITLE
Incompatible with Rails 6

### ISSUE THREAD

**Issue by shushugah** [jsonapi-rb/jsonapi-serializable#116]
As of version `0.4.0` the dependencies are set to `rails ~> 5.0`, so we cannot upgrade to rails 6 right now

**Comment by Samsinite** [comment]
Randomly came across this issue, looks like this is currently not a problem, the only dependency is on jsonapi-renderer, which has no dependencies (other than ruby, see https://github.com/jsonapi-rb/jsonapi-serializable/blob/master/jsonapi-serializable.gemspec#L17). @shushugah want to close this issue?

**Comment by shushugah** [comment]
I made a mistake and meant this for https://github.com/jsonapi-rb/jsonapi-rails/issues/117
