### ISSUE TITLE
Pagination Links

### ISSUE THREAD

**Issue by richmolj** [jsonapi-rb/jsonapi-serializable#52]
I personally don't see a good use case for pagination links, my thoughts are summed up in https://github.com/jsonapi-suite/jsonapi_suite/issues/3#issuecomment-273486148

However, wanted to raise the issue and see - if there is a valid use case - if this library shoulders the responsibility.

**Comment by andreaseger** [comment]
IMHO pagination links are great. With these links the client doesn't need to know how to get the next/prev/first/last page.
And if the client wants to additionally know the overall count of the collection this could be passed along as field in meta.

I'm not sure though if this can be made generic enough to let a low level library take care of them. It would need to know quite a bit context about the current request like filter options, sort options, what pagination strategy is used (page or offset based) and the overall count of the collection. IMHO this is better left to the application at a higher level itself

**Comment by richmolj** [comment]
> IMHO pagination links are great. With these links the client doesn't need to know how to get the next/prev/first/last page.

I hear you. Doesn't the client already know next/prev automatically, though, via the page[number] parameter? I'm still struggling to see the real benefit of these links...if you're writing a client that knows how to query jsonapi, this seems fairly trivial to implement.

**Comment by andreaseger** [comment]
Well that depends on the server. Jsonapi doesn't really define much about pagination and how it should be handled.
A use case where these links become important is if the server wants to enforce a max page size to prevent the client to make huge requests. This could be implemented in a way that if the given pagesize is bigger than the max the request won't fail but only returns a page with the max page size. Then the client needs to know how to get the next page -> the next link which correctly considers the configured max pagesize.
As the client already does pagination based on these links it should be fairly easy to be able to receive less than the expected number of items.
So it's not always just +1 to the page number.

**Comment by beauby** [comment]
@richmolj If you use cursor-based pagination then the client has no way to guess the cursors for the previous/next pages.

As there is no standard way of representing paginated collections in ruby, I wouldn't want to include automatic pagination in this gem, although I think a how-to on the website could be useful (one possibility is to override the `render` method to automatically add the relevant links).

**Comment by richmolj** [comment]
@beauby good point, hadn't considered that.

Is there something like 'default_render_options', maybe, to avoid a straight-up override?

**Comment by beauby** [comment]
@richmolj Not really. I'm thinking about adding some hooks in `jsonapi-rails`/`jsonapi-hanami` for this, but haven't found a fully satisfying way yet.

**Comment by beauby** [comment]
Closing this in favor of https://github.com/jsonapi-rb/jsonapi-rails/pull/35.
