### ISSUE TITLE
Rendering plain single Sequel Model object failed

### ISSUE THREAD

**Issue by luciusgone** [jsonapi-rb/jsonapi-serializable#57]
Here is the code

```
require 'sqlite3'
require 'sequel'

DB = Sequel.sqlite
DB.create_table :items do
  primary_key :id
  String :name
  Float :price
end

items = DB[:items]

items.insert(:name => 'abc', :price => rand * 100)
items.insert(:name => 'def', :price => rand * 100)
items.insert(:name => 'ghi', :price => rand * 100)

class Item < Sequel::Model
end

require 'json'
require 'jsonapi/serializable'

class SerializableItem < JSONAPI::Serializable::Resource
  type 'item'
  
  attributes :name, :price
end

all_items = Item.all
first_item = Item.first

renderer = JSONAPI::Serializable::Renderer

renderer.render(all_items, class: SerializableItem) # this works

renderer.render(first_item, class: SerializableItem) # this does not work
```

I'm pretty sure the problem is originated in the  JSONAPI::Serializable::ResourceBuilder class where it checks if passed in objects respond to "each" and actually call "map" method.

Can we just check the passed in object respond to "map" method instead of "each"?

**Comment by beauby** [comment]
Hi @luciusgone – thanks for reporting this. I remember identifying this bug a while back (Sequel, for some reason, implements `#each` on models such as it iterates over the fields), and implementing a fix (namely checking for `#to_ary` instead of `#each`) but it got lost somehow. Will issue a PR immediately :+1:.

**Comment by beauby** [comment]
@luciusgone I just tested your code with #58 and it seems to work fine :+1:.
