### ISSUE TITLE
Check for #each, but then #maps?

### ISSUE THREAD

**Issue by Aryk** [jsonapi-rb/jsonapi-serializable#60]
in ResourceBuilder:

```ruby
      def self.build(objects, expose, klass)
        return objects if objects.nil? ||
                          Array(objects).first.respond_to?(:as_jsonapi)

        if objects.respond_to?(:each)
          objects.map { |obj| new(obj, expose, klass).resource }
        else
          new(objects, expose, klass).resource
        end
      end
```

We check if it responds to #each, but then actually run #map on it. If it is a Sequel::Model, this will throw an error since #each will return an enumerator over the attributes of the record. However, there is no #map function so it will return an error.

I think this should be `objects.respond_to?(:map)`

are you ok with that change @beauby ?

**Comment by Aryk** [comment]
Nevermind, closing this, seems i dont have the newest version of the library.

**Comment by beauby** [comment]
Hi @Aryk – thanks for looking into this. It was fixed by [this commit](https://github.com/jsonapi-rb/jsonapi-serializable/commit/5df50d772ffb004f072b11194662b24345842a55) but hasn't been released yet.

**Comment by Aryk** [comment]
Yeah, I had to pull the master branch in  order to get things working on my end, but it is working with that commit.
