### ISSUE TITLE
Rendering errors

### ISSUE THREAD

**Issue by cmavromoustakos** [jsonapi-rb/jsonapi-serializable#88]
Hello

I am trying to render errors and can not seem to find any documentation on how to accomplish this cleanly. 

I tried following the example given here:

https://github.com/jsonapi-rb/jsonapi-serializable/blob/master/lib/jsonapi/serializable/renderer.rb#L61

But received the error below. 

I can continue to look through the code to figure it out, but it would be nice if this was covered a little more thoroughly on the documentation.

Thank you

```
[2] pry(CBP::Authentication::API)> error = JSONAPI::Serializable::Error.create(id: 'foo', 
title: 'bar')

[6] pry(CBP::Authentication::API)> renderer = JSONAPI::Serializable::Renderer.new
=> #<JSONAPI::Serializable::Renderer:0x000055bd5d1a9288  
@renderer=#<JSONAPI::Renderer:0x000055bd5d1a9260>>

[7] pry(CBP::Authentication::API)> renderer.render_errors([error]) 
NoMethodError: undefined method `new' for nil:NilClass from
/usr/local/bundle/gems/jsonapi-serializable-0.3.0/lib/jsonapi/serializable/renderer.rb:88 :in `_build'

[8] pry(CBP::Authentication::API)>
```

**Comment by xrav3nz** [comment]
Also new to `jsonapi-rb`.

I've been running into the same problem: `Renderer` actually expects a `class` kwarg that maps a type to its corresponding serializer. 

i.e. something along the line of

```ruby
renderer.render_errors(error, class: { Error: JSONAPI::Serializable::Error })
```

_should_ fix your problem.
