### ISSUE TITLE
Error when trying to render a Module class

### ISSUE THREAD

**Issue by mde-pach** [jsonapi-rb/jsonapi-serializable#96]
When I want to render a module class using the jsonapi-serializable, the create sym is incorrect because of the module name (`Module::Class` instead of expected `Class`). In my case, I solve locally the problem by adding a rails String `demodulize` in the `lib/jsonapi/serializable.rb` but it's a rails String property not a ruby one.

I do a PR with the rails implementation of the demodulize to solve this case.

**Comment by beauby** [comment]
As said on the PR, you can do `"Module::Class".to_sym` or `:"Module::Class"`.
